name: dev-site
services:
  build:
    build: .
    volumes:
      - ".:/src/"
    command: obsidian-export -h
  serve:
    image: klakegg/hugo:0.101.0-ubuntu
    command: server -D 
    volumes:
      - ".:/src"
    ports: 
        - "1313:1313"