name: dev-site
services:
  build:
    build: .
    volumes:
      - "./vault:/src/vault"
      - "./content:/src/content"
    develop:
      watch:
        - action: rebuild
          path: ./vault
  server:
    image: klakegg/hugo:ext-ubuntu
    command: server -D
    volumes:
      - ".:/src/"
    ports: 
        - "1313:1313"
