# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "hugo" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache cargo plugins
        id: cache-obsidian-export
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: Install obsidian-export
        if: steps.cache-obsidian-export.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1
        with:
          crate: obsidian-export
          version: latest

      - name: Create content directory
        shell: bash
        run: mkdir -p ./content

      - name: Export Vault
        shell: bash
        run: obsidian-export ./vault ./content/

      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          image: ext-ubuntu

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: public/

  # Deploy job
  # deploy:
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4 
